version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  storing-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "50051:50051"
    command: ["./storing-service", "--config=config/local.yaml"]

volumes:
  pgdata:
