grpc:
  port: "50052"

postgres:
  dsn: "postgres://user:password@order-postgres:5433/orders?sslmode=disable"

kafka:
  broker: "localhost:9092"
  topic: "order_created"
  group_id: "orders-service-group"
