version: '3.9'

services:
  payments-postgres:
    image: postgres:15
    container_name: payments-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payments-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    container_name: payments-service
    depends_on:
      payments-postgres:
        condition: service_healthy
    ports:
      - "50051:50051"
    volumes:
      - ./config:/app/config

volumes:
  pgdata:
